version : '3'
services:
  react-web:
        build : 
            context: .
            dockerfile: dockerfile.dev
        ports:
            - 3000:3000
        volumes:
            - /app/nodes_modules   
            - .:/app                   
  